language: java
sudo: false
services:
- docker
cache:
  directories:
  - "$HOME/.cache"

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true

default_text_charset: 'utf-8'

addons:
  apt:
    packages:
      - oracle-java8-installer
    
branches:
  only:
    - master

install:
  -
