language: java
sudo: false
services:
- docker
jdk: openjdk8
cache:
  directories:
    - $HOME/.m2
dist: xenial
script: | 
    mvn test
after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true

default_text_charset: 'utf-8'

addons:
  apt:
    packages:
      - oracle-java8-installer
    
branches:
  only:
    - master

notifications:
  email:
    - a.riccio26@studenti.unisa.it
